### ISSUE TITLE
Does nalu-wind need to load modules?

### ISSUE THREAD

**Issue by aprokop** [sayerhs/exawind-builder#2]
Right now, `nalu-wind` tries to load non-standard modules like `trilinos`, `yaml-cpp`, etc. This breaks on `cori`. I expect that because paths are passed through cmake arguments, that is unnecessary. In addition, loading of `hypre`, `tioga`, should really depend on whether Hypre or Tioga are enabled in cmake arguments, which is tricky.

**Comment by aprokop** [comment]
Per @sayerhs:

In the `./nalu-wind-haswell.sh` script you can export variables like
```
ENABLE_HYPRE=OFF
ENABLE_OPENFAST=OFF
ENABLE_TIOGA=OFF
```

And you can disable loading of any of the modules by passing
```
OPENFAST_ROOT_DIR=$(pwd)
TIOGA_ROOT_DIR=$(pwd)
HYPRE_ROOT_DIR=$(pwd)
```
With this combination you can disable any of the Nalu-wind TPLs
It would be nice if the modules weren't loaded if `ENABLE_HYPRE` was off... but then that logic won't work if hypre is mandatory dependency
so I opted for this two step option

**Comment by sayerhs** [comment]
See example below to disable all optional TPLs for `nalu-wind`

```
### Add this to the "nalu-wind-COMPILER.sh" script just before the actual execution 
### section at the end of the file

#
# Override the default dependency loader; always need yaml-cpp and Trilinos
# 
exawind_proj_env ()
{
    exawind_load_deps trilinos yaml-cpp
}

#
# Disable all TPLS
#
ENABLE_OPENFAST=OFF
ENABLE_TIOGA=OFF
ENABLE_HYPRE=OFF
```
