### ISSUE TITLE
EXAWIND_NUM_JOBS does not work

### ISSUE THREAD

**Issue by aprokop** [sayerhs/exawind-builder#5]
@sayerhs 

I tried both
```
EXAWIND_NUM_JOBS=16
```
and
```
export EXAWIND_NUM_JOBS=16
```
in my trilinos script on cori, but I still see it compiling with just 8.

**Comment by sayerhs** [comment]
@aprokop You should now be able to use `EXAWIND_NUM_JOBS=16` in the driver script.
